/* ═══════════════════════════════════════════════════════════════════
   The public half of the licence signing key, and the check that uses it.

   A licence is an ECDSA P-256 signature over a statement of the form
   "user U owns skill S major version V until T". Kerf verifies it here,
   with no network, which is the entire reason licences are signed
   rather than looked up: a skill somebody paid for has to open on a
   laptop with no connection, and in the market this is being built for
   that is the normal case rather than the edge one.

   **Verification is not authorisation for the seller.** The store
   re-checks the entitlement table on every download. This is what lets
   an ALREADY-INSTALLED skill run, and nothing more. Someone determined
   can patch it out — Kerf is MIT and this file ships as source — and
   that is accounted for in HANDOVER §6: skills are revocable managed
   extensions and the store's value is updates, verification and
   convenience, not a lock.

   ROTATION: add the new key to the front of the array and keep the old
   one until every licence signed by it has expired (30 days). Replacing
   the entry instead of appending would invalidate every licence in the
   field at once.
   ═══════════════════════════════════════════════════════════════════ */

export interface LicencePayload {
  sub: string;
  skill: string;
  ver: number;
  jti: string;
  iat: number;
  exp: number;
}

/**
 * The DEVELOPMENT key.
 *
 * Kept, named, and exported so it can be ASSERTED AGAINST. It is the
 * only value that must never be the sole trusted key in a shipped
 * build, and `licenceKey.test.ts` fails if it is — see the note on
 * PRODUCTION_KEY below for why that check had to exist.
 */
export const DEV_PUBLIC_KEY: JsonWebKey = {
  kty: 'EC',
  crv: 'P-256',
  x: 'JbqEqZGO8AEut8YCsnSlK64_4-UnS8lM6MYVSDt-uWA',
  y: 'c6PiawLFeb18QClm5ZRr-3o-S4av3qZZI88O0FOBvn4',
};

/**
 * The production signing key.
 *
 * Its private half lives ONLY in `server/.secrets/licence-signing.jwk`
 * (0600, gitignored) and in the Worker's `LICENCE_SIGNING_JWK` secret.
 * If those two ever disagree, every licence in the field stops
 * verifying at once and every paying customer is locked out of what
 * they bought — which is the single worst failure this system has, and
 * the reason `licenceKey.test.ts` exists.
 */
export const PRODUCTION_KEY: JsonWebKey = {
  kty: 'EC',
  crv: 'P-256',
  x: '3B8-0fiuvnriDuuiADtkw8SQwsf_h8twpes2mrd1oU4',
  y: 'wnmqm3II0MAGbRlcCLQPt17O6B-_H68Ep6e_1QYXtI0',
};

/**
 * Which keys this build trusts.
 *
 * **The dev key is trusted in DEV BUILDS ONLY, and that is the whole
 * point of this function.** The first version of this file simply
 * listed both keys, which would have been a hole big enough to drive a
 * bus through: the dev key's PRIVATE half is generated by a script in
 * this repo and printed to a terminal, so anybody could mint themselves
 * a licence for any skill and a shipped build would have accepted it.
 *
 * Taking a boolean rather than reading `import.meta.env.DEV` directly is
 * what makes it testable — `trustedKeys(false)` is the production answer
 * and a test can assert the dev key is not in it. A check that can only
 * observe the environment it runs in cannot fail in the case that
 * matters.
 *
 * ROTATION: prepend the new production key and keep the old one until
 * every licence signed by it has expired (30 days). Replacing the entry
 * instead of prepending invalidates every licence in the field at once.
 */
export function trustedKeys(isDev: boolean): JsonWebKey[] {
  return isDev ? [PRODUCTION_KEY, DEV_PUBLIC_KEY] : [PRODUCTION_KEY];
}

export const LICENCE_PUBLIC_KEYS: JsonWebKey[] = trustedKeys(
  // Vite replaces this at build time; it is the same switch that decides
  // whether `window.__kerf` exists.
  Boolean(import.meta.env?.DEV)
);

/* Returns an ArrayBuffer rather than a Uint8Array: TypeScript 5.7's
   `BufferSource` will not accept `Uint8Array<ArrayBufferLike>`, because
   the backing store could in principle be a SharedArrayBuffer, and
   WebCrypto refuses those. */
function fromB64Url(s: string): ArrayBuffer {
  const pad = s.replace(/-/g, '+').replace(/_/g, '/');
  const bin = atob(pad + '='.repeat((4 - (pad.length % 4)) % 4));
  const out = new Uint8Array(new ArrayBuffer(bin.length));
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out.buffer;
}

export type LicenceVerdict =
  | { valid: true; payload: LicencePayload }
  | { valid: false; reason: 'malformed' | 'bad_signature' | 'expired'; payload?: LicencePayload };

/**
 * Verify a compact licence.
 *
 * Order matters: signature BEFORE expiry. Reading `exp` out of a payload
 * whose signature has not been checked is reading a number the holder
 * chose, and reporting "expired" for a forgery would send someone to
 * the store to renew something that was never real.
 */
export async function verifyLicence(
  compact: string,
  keys: JsonWebKey[] = LICENCE_PUBLIC_KEYS
): Promise<LicenceVerdict> {
  const parts = compact.split('.');
  if (parts.length !== 3) return { valid: false, reason: 'malformed' };
  const [header, body, sig] = parts;

  const signed = new TextEncoder().encode(`${header}.${body}`);
  let signatureOk = false;

  for (const jwk of keys) {
    try {
      const key = await crypto.subtle.importKey(
        'jwk', { ...jwk, key_ops: ['verify'], ext: true },
        { name: 'ECDSA', namedCurve: 'P-256' }, false, ['verify']
      );
      if (await crypto.subtle.verify({ name: 'ECDSA', hash: 'SHA-256' }, key, fromB64Url(sig), signed)) {
        signatureOk = true;
        break;
      }
    } catch {
      /* A key that will not import is a key that cannot vouch for this
         licence. Try the next one rather than failing the whole check. */
    }
  }
  if (!signatureOk) return { valid: false, reason: 'bad_signature' };

  let payload: LicencePayload;
  try {
    payload = JSON.parse(new TextDecoder().decode(new Uint8Array(fromB64Url(body)))) as LicencePayload;
  } catch {
    return { valid: false, reason: 'malformed' };
  }

  if (typeof payload.exp !== 'number' || payload.exp < Date.now()) {
    // Signed, genuinely theirs, and past its window. The UI says
    // "reconnect to refresh", not "you do not own this".
    return { valid: false, reason: 'expired', payload };
  }
  return { valid: true, payload };
}
