/*
 * The licence verifier, and the two mistakes that would be catastrophic.
 *
 * 1. Shipping a build that trusts the DEV key. Its private half is
 *    generated by a script in this repo and printed to a terminal, so a
 *    production build that trusts it would accept a licence anybody
 *    could mint. `trustedKeys(false)` is the production answer and the
 *    test asserts the dev key is not in it.
 *
 * 2. Shipping a build whose production key does not match the Worker's
 *    signing secret. Every real licence then fails to verify and every
 *    paying customer is locked out of what they bought. Nothing in a
 *    unit test can compare against a secret it must not have — so what
 *    is asserted here is that the production key is PRESENT, DISTINCT
 *    from dev, and a well-formed P-256 point that WebCrypto will import.
 *    A typo'd or truncated key fails that last one.
 *
 * The verifier itself is exercised against a keypair generated in the
 * test, which is why `verifyLicence` takes its key list as a parameter:
 * a check that can only run against the real key could not run in CI.
 */
import { describe, it, expect } from 'vitest';
import {
  verifyLicence, trustedKeys, DEV_PUBLIC_KEY, PRODUCTION_KEY, type LicencePayload,
} from './licenceKey';

const enc = new TextEncoder();
const b64u = (b: Uint8Array) => Buffer.from(b).toString('base64url');

async function makeKey() {
  return crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']);
}

async function sign(priv: CryptoKey, payload: LicencePayload): Promise<string> {
  const header = b64u(enc.encode(JSON.stringify({ alg: 'ES256', typ: 'kerf-licence' })));
  const body = b64u(enc.encode(JSON.stringify(payload)));
  const sig = await crypto.subtle.sign(
    { name: 'ECDSA', hash: 'SHA-256' }, priv, enc.encode(`${header}.${body}`)
  );
  return `${header}.${body}.${b64u(new Uint8Array(sig))}`;
}

const payload = (over: Partial<LicencePayload> = {}): LicencePayload => ({
  sub: 'usr_1', skill: 'beat-montage', ver: 1, jti: 'ent_1',
  iat: Date.now(), exp: Date.now() + 30 * 86400_000, ...over,
});

describe('which keys a build trusts', () => {
  it('never trusts the dev key in a production build', () => {
    const prod = trustedKeys(false);
    expect(prod).toHaveLength(1);
    expect(prod.some((k) => k.x === DEV_PUBLIC_KEY.x)).toBe(false);
  });

  it('does trust it in a dev build, so a local Worker still works', () => {
    expect(trustedKeys(true).some((k) => k.x === DEV_PUBLIC_KEY.x)).toBe(true);
  });

  it('always trusts production, in both builds', () => {
    for (const isDev of [true, false]) {
      expect(trustedKeys(isDev)[0].x).toBe(PRODUCTION_KEY.x);
    }
  });

  it('the production key was actually replaced, not left as dev', () => {
    expect(PRODUCTION_KEY.x).not.toBe(DEV_PUBLIC_KEY.x);
    expect(PRODUCTION_KEY.y).not.toBe(DEV_PUBLIC_KEY.y);
  });

  it('the production key is a P-256 point WebCrypto will import', async () => {
    // Catches a truncated or mistyped coordinate, which would otherwise
    // surface as "every licence is invalid" on the day of launch.
    await expect(crypto.subtle.importKey(
      'jwk', { ...PRODUCTION_KEY, key_ops: ['verify'], ext: true },
      { name: 'ECDSA', namedCurve: 'P-256' }, false, ['verify']
    )).resolves.toBeDefined();
  });
});

describe('verifying a licence', () => {
  it('accepts one signed by a trusted key', async () => {
    const { privateKey, publicKey } = await makeKey();
    const jwk = await crypto.subtle.exportKey('jwk', publicKey);
    const licence = await sign(privateKey, payload());

    const verdict = await verifyLicence(licence, [jwk]);
    expect(verdict.valid).toBe(true);
    if (verdict.valid) expect(verdict.payload.skill).toBe('beat-montage');
  });

  it('rejects one signed by a key it does not trust', async () => {
    const mine = await makeKey();
    const theirs = await makeKey();
    const jwk = await crypto.subtle.exportKey('jwk', theirs.publicKey);

    const verdict = await verifyLicence(await sign(mine.privateKey, payload()), [jwk]);
    expect(verdict.valid).toBe(false);
    if (!verdict.valid) expect(verdict.reason).toBe('bad_signature');
  });

  it('rejects one whose claim was edited after signing', async () => {
    const { privateKey, publicKey } = await makeKey();
    const jwk = await crypto.subtle.exportKey('jwk', publicKey);
    const licence = await sign(privateKey, payload({ skill: 'beat-montage' }));

    const [h, , s] = licence.split('.');
    const swapped = `${h}.${Buffer.from(
      JSON.stringify(payload({ skill: 'cinematic-grade' }))
    ).toString('base64url')}.${s}`;

    const verdict = await verifyLicence(swapped, [jwk]);
    expect(verdict.valid).toBe(false);
    if (!verdict.valid) expect(verdict.reason).toBe('bad_signature');
  });

  it('reports an expired licence as expired, not as a forgery', async () => {
    // The distinction is the whole UI difference between "connect once
    // to refresh" and "you do not own this".
    const { privateKey, publicKey } = await makeKey();
    const jwk = await crypto.subtle.exportKey('jwk', publicKey);
    const licence = await sign(privateKey, payload({ exp: Date.now() - 1000 }));

    const verdict = await verifyLicence(licence, [jwk]);
    expect(verdict.valid).toBe(false);
    if (!verdict.valid) {
      expect(verdict.reason).toBe('expired');
      expect(verdict.payload?.skill).toBe('beat-montage');
    }
  });

  it('checks the signature BEFORE the expiry', async () => {
    // A forgery that also happens to be expired must read as a forgery.
    // Reading `exp` out of an unverified payload is reading a number the
    // holder chose.
    const mine = await makeKey();
    const theirs = await makeKey();
    const jwk = await crypto.subtle.exportKey('jwk', theirs.publicKey);
    const licence = await sign(mine.privateKey, payload({ exp: Date.now() - 1000 }));

    const verdict = await verifyLicence(licence, [jwk]);
    expect(verdict.valid).toBe(false);
    if (!verdict.valid) expect(verdict.reason).toBe('bad_signature');
  });

  it('rejects a licence that is not three segments', async () => {
    for (const junk of ['', 'a', 'a.b', 'a.b.c.d']) {
      const verdict = await verifyLicence(junk, [PRODUCTION_KEY]);
      expect(verdict.valid).toBe(false);
    }
  });
});
