import { contextBridge, ipcRenderer } from 'electron';

/** Shape of the update state pushed from the main process. */
export type UpdateStatus =
  | { state: 'idle' }
  | { state: 'checking' }
  | { state: 'available'; version: string; notes?: string }
  | { state: 'downloading'; version: string; percent: number; bytesPerSecond: number }
  | { state: 'ready'; version: string }
  | { state: 'up-to-date'; version: string }
  | { state: 'manual-only'; version: string; url: string }
  | { state: 'error'; message: string };

export interface ClaudeStatus {
  installed: boolean;
  path: string | null;
  version: string | null;
  running: boolean;
}

export interface ElectronAPI {
  openMediaDialog: () => Promise<string[] | null>;
  saveExportDialog: (defaultName: string) => Promise<string | null>;
  platform: string;

  /** Serves external tool calls from the process that owns the project. */
  bridge: {
    onListTools: (cb: (id: string) => void) => void;
    onCallTool: (cb: (id: string, name: string, args: Record<string, unknown>) => void) => void;
    respond: (payload: { id: string; ok: boolean; data?: unknown; error?: string }) => void;
  };

  /** On-device speech-to-text (ffmpeg + Whisper, run in main). */
  stt: {
    status: () => Promise<{ ffmpeg: string | null; whisper: string | null; models: string[]; ready: boolean }>;
    transcribe: (opts: { mediaUrl: string; language?: string; model?: string }) => Promise<any>;
    analyze: (opts: { mediaUrl: string; silenceThresholdDb?: number; minSilenceMs?: number }) => Promise<any>;
    setup: (opts?: { model?: string }) => Promise<any>;
    onProgress: (cb: (p: { percent: number; note: string }) => void) => () => void;
  };

  /** Real video export: frames to ffmpeg, audio muxed in. */
  exporter: {
    start: (opts: any) => Promise<{ sessionId?: string; error?: string }>;
    frame: (sessionId: string, jpeg: Uint8Array) => Promise<{ ok: boolean; error?: string }>;
    finish: (sessionId: string, audioClips: any[]) => Promise<any>;
    cancel: (sessionId: string) => Promise<boolean>;
  };

  /** Write generated bytes to a temp file, so ffmpeg can read them. */
  media: {
    writeTemp: (name: string, bytes: Uint8Array) => Promise<string>;
    /**
     * Enumerate a folder. The renderer cannot: `fetch`/XHR on a `file://`
     * directory both fail even with webSecurity off. Reports names, sizes
     * and timestamps only — whether a file is usable media is decided by
     * trying to decode it, not by its extension.
     */
    listFolder: (
      path: string,
      recursive?: boolean
    ) => Promise<{
      ok: boolean;
      folder?: string;
      entries?: {
        name: string; path: string; kind: 'file' | 'directory' | 'other';
        sizeBytes: number; mtimeMs: number; birthtimeMs: number;
      }[];
      unreadable?: { name: string; reason: string }[];
      error?: string;
    }>;
  };

  project: {
    read: (path: string) => Promise<{ ok: boolean; json?: string; error?: string }>;
    write: (path: string, json: string) => Promise<{ ok: boolean; bytes?: number; error?: string }>;
  };

  ffmpeg: {
    process: (opts: {
      input: string; vf?: string; af?: string; fps?: number;
      codec?: 'h264' | 'prores'; noAudio?: boolean; audioOnly?: boolean; name?: string;
    }) => Promise<{ ok: boolean; path?: string; bytes?: number; error?: string }>;
  };

  /** Renderer failures, into the log file main owns. */
  crash: {
    report: (payload: { message: string; detail?: string; source?: string })
      => Promise<{ ok: boolean; logPath: string }>;
    logPath: () => Promise<string>;
  };

  /** Screen state, so the window close button can mean the right thing. */
  ui: {
    setScreen: (screen: 'home' | 'editor') => Promise<boolean>;
    onGoHome: (cb: () => void) => () => void;
  };

  /** The Kerf Store session token, held at 0600 in main rather than
      in the renderer's localStorage. */
  store: {
    getSession: () => Promise<{ session: { token: string; expiresAt: number } | null; baseUrl: string }>;
    setSession: (token: string, expiresAt: number) => Promise<boolean>;
    clearSession: () => Promise<boolean>;
  };

  /** Which CLI backend drives the Copilot, and getting one installed. */
  agents: {
    list: (deep?: boolean) => Promise<{ selected: string; backends: unknown[] }>;
    select: (id: string) => Promise<string>;
    install: (id: string) => Promise<{ ok: boolean; message: string }>;
    setKey: (variable: string, value: string) => Promise<boolean>;
    recheck: () => Promise<boolean>;
    models: (id: string) => Promise<{ models: string[]; source: string; selected: string }>;
    setModel: (id: string, model: string) => Promise<boolean>;
    signIn: (id: string) => Promise<{ ok: boolean; message: string }>;
    onInstallProgress: (cb: (p: { id: string; line: string }) => void) => () => void;
  };

  /** The Claude Code session that powers the Copilot. */
  claude: {
    status: () => Promise<ClaudeStatus>;
    send: (prompt: string, resume: boolean) => Promise<boolean>;
    stop: () => Promise<boolean>;
    reset: () => Promise<boolean>;
    onEvent: (cb: (event: Record<string, unknown>) => void) => () => void;
  };

  updater: {
    /** Current state, for the first render before any event arrives. */
    getStatus: () => Promise<UpdateStatus>;
    getCurrentVersion: () => Promise<string>;
    /** User-initiated check. Background checks happen on their own. */
    check: () => Promise<UpdateStatus>;
    /** Quit and apply a downloaded update. No-op unless state is `ready`. */
    install: () => Promise<boolean>;
    /** Fallback for builds that cannot self-update. */
    openReleases: () => Promise<void>;
    /** Subscribe to state changes; returns an unsubscribe function. */
    onStatus: (cb: (status: UpdateStatus) => void) => () => void;
  };
}

const api: ElectronAPI = {
  openMediaDialog: () => ipcRenderer.invoke('dialog:openMedia'),
  saveExportDialog: (defaultName: string) => ipcRenderer.invoke('dialog:saveExport', defaultName),
  platform: process.platform,

  bridge: {
    onListTools: (cb) => {
      ipcRenderer.on('bridge:list-tools', (_e, msg: { id: string }) => cb(msg.id));
    },
    onCallTool: (cb) => {
      ipcRenderer.on(
        'bridge:call-tool',
        (_e, msg: { id: string; payload: { name: string; args: Record<string, unknown> } }) =>
          cb(msg.id, msg.payload.name, msg.payload.args)
      );
    },
    respond: (payload) => ipcRenderer.send('bridge:response', payload),
  },

  stt: {
    status: () => ipcRenderer.invoke('stt:status'),
    transcribe: (opts) => ipcRenderer.invoke('stt:transcribe', opts),
    analyze: (opts) => ipcRenderer.invoke('audio:analyze', opts),
    setup: (opts) => ipcRenderer.invoke('stt:setup', opts ?? {}),
    onProgress: (cb) => {
      const handler = (_e: unknown, p: { percent: number; note: string }) => cb(p);
      ipcRenderer.on('stt:progress', handler);
      return () => ipcRenderer.removeListener('stt:progress', handler);
    },
  },

  exporter: {
    start: (opts) => ipcRenderer.invoke('export:start', opts),
    frame: (sessionId, jpeg) => ipcRenderer.invoke('export:frame', { sessionId, jpeg }),
    finish: (sessionId, audioClips) => ipcRenderer.invoke('export:finish', { sessionId, audioClips }),
    cancel: (sessionId) => ipcRenderer.invoke('export:cancel', { sessionId }),
  },

  media: {
    writeTemp: (name, bytes) => ipcRenderer.invoke('media:writeTemp', { name, bytes }),
    listFolder: (path, recursive) => ipcRenderer.invoke('media:listFolder', { path, recursive }),
  },

  project: {
    read: (filePath) => ipcRenderer.invoke('project:read', { path: filePath }),
    write: (filePath, json) => ipcRenderer.invoke('project:write', { path: filePath, json }),
  },

  ffmpeg: {
    process: (opts) => ipcRenderer.invoke('ffmpeg:process', opts),
  },

  crash: {
    report: (payload) => ipcRenderer.invoke('crash:report', payload),
    logPath: () => ipcRenderer.invoke('crash:logPath'),
  },
  ui: {
    setScreen: (screen) => ipcRenderer.invoke('ui:setScreen', { screen }),
    onGoHome: (cb) => {
      const handler = () => cb();
      ipcRenderer.on('ui:go-home', handler);
      return () => ipcRenderer.removeListener('ui:go-home', handler);
    },
  },

  store: {
    getSession: () => ipcRenderer.invoke('store:getSession'),
    setSession: (token, expiresAt) => ipcRenderer.invoke('store:setSession', { token, expiresAt }),
    clearSession: () => ipcRenderer.invoke('store:clearSession'),
  },

  agents: {
    list: (deep) => ipcRenderer.invoke('agents:list', { deep }),
    select: (id) => ipcRenderer.invoke('agents:select', { id }),
    install: (id) => ipcRenderer.invoke('agents:install', { id }),
    setKey: (variable, value) => ipcRenderer.invoke('agents:setKey', { variable, value }),
    recheck: () => ipcRenderer.invoke('agents:recheck'),
    models: (id) => ipcRenderer.invoke('agents:models', { id }),
    setModel: (id, model) => ipcRenderer.invoke('agents:setModel', { id, model }),
    signIn: (id) => ipcRenderer.invoke('agents:signIn', { id }),
    onInstallProgress: (cb) => {
      const handler = (_e: unknown, p: { id: string; line: string }) => cb(p);
      ipcRenderer.on('agents:install-progress', handler);
      return () => ipcRenderer.removeListener('agents:install-progress', handler);
    },
  },

  claude: {
    status: () => ipcRenderer.invoke('claude:status'),
    send: (prompt: string, resume: boolean) => ipcRenderer.invoke('claude:send', { prompt, resume }),
    stop: () => ipcRenderer.invoke('claude:stop'),
    reset: () => ipcRenderer.invoke('claude:reset'),
    onEvent: (cb) => {
      const handler = (_e: unknown, event: Record<string, unknown>) => cb(event);
      ipcRenderer.on('claude:event', handler);
      return () => ipcRenderer.removeListener('claude:event', handler);
    },
  },

  updater: {
    getStatus: () => ipcRenderer.invoke('updater:status'),
    getCurrentVersion: () => ipcRenderer.invoke('updater:currentVersion'),
    check: () => ipcRenderer.invoke('updater:check'),
    install: () => ipcRenderer.invoke('updater:install'),
    openReleases: () => ipcRenderer.invoke('updater:openReleases'),
    onStatus: (cb) => {
      const handler = (_e: unknown, status: UpdateStatus) => cb(status);
      ipcRenderer.on('updater:status', handler);
      return () => ipcRenderer.removeListener('updater:status', handler);
    },
  },
};

contextBridge.exposeInMainWorld('electronAPI', api);
