import { contextBridge, ipcRenderer } from 'electron';

/** Shape of the update state pushed from the main process. */
export type UpdateStatus =
  | { state: 'idle' }
  | { state: 'checking' }
  | { state: 'available'; version: string; notes?: string }
  | { state: 'downloading'; version: string; percent: number; bytesPerSecond: number }
  | { state: 'ready'; version: string }
  | { state: 'up-to-date'; version: string }
  | { state: 'manual-only'; version: string; url: string }
  | { state: 'error'; message: string };

export interface ClaudeStatus {
  installed: boolean;
  path: string | null;
  version: string | null;
  running: boolean;
}

/** One capturable display or window, as `desktopCapturer` sees it. */
export interface RecorderSource {
  id: string;
  name: string;
  kind: 'screen' | 'window';
  displayId: number | null;
  /** Real captured pixels. Null for a window, whose size is only known once its stream starts. */
  width: number | null;
  height: number | null;
  scaleFactor: number;
  primary: boolean;
  thumbnail: string | null;
  icon: string | null;
}

export type MediaAccess = 'not-determined' | 'granted' | 'denied' | 'restricted' | 'unknown';

export interface RecorderPermissions {
  platform: string;
  screen: MediaAccess;
  camera: MediaAccess;
  microphone: MediaAccess;
  /** False on Linux, where the control bar cannot be kept out of the capture. */
  barHiddenFromCapture: boolean;
}

export interface TrialStatus {
  skillId: string;
  allowed: number;
  used: number;
  remaining: number;
  canRun: boolean;
  /* 'granted' means an earlier run already covered this subject, so it
     costs nothing. 'unlimited' was in this union and the policy never
     produced it; a value no code path can return is a branch every
     reader has to rule out by hand. */
  reason: 'owned' | 'not-gated' | 'granted' | 'trial' | 'exhausted' | 'tampered';
  message: string;
  trialsAreLocal: boolean;
}

export interface ElectronAPI {
  openMediaDialog: () => Promise<string[] | null>;
  saveExportDialog: (defaultName: string) => Promise<string | null>;
  platform: string;

  /** Serves external tool calls from the process that owns the project. */
  bridge: {
    onListTools: (cb: (id: string) => void) => void;
    onCallTool: (cb: (id: string, name: string, args: Record<string, unknown>) => void) => void;
    respond: (payload: { id: string; ok: boolean; data?: unknown; error?: string }) => void;
  };

  /** On-device speech-to-text (ffmpeg + Whisper, run in main). */
  stt: {
    status: () => Promise<{ ffmpeg: string | null; whisper: string | null; models: string[]; ready: boolean }>;
    transcribe: (opts: { mediaUrl: string; language?: string; model?: string }) => Promise<any>;
    analyze: (opts: { mediaUrl: string; silenceThresholdDb?: number; minSilenceMs?: number }) => Promise<any>;
    setup: (opts?: { model?: string }) => Promise<any>;
    onProgress: (cb: (p: { percent: number; note: string }) => void) => () => void;
  };

  /** Real video export: frames to ffmpeg, audio muxed in. */
  exporter: {
    start: (opts: any) => Promise<{ sessionId?: string; error?: string }>;
    frame: (sessionId: string, jpeg: Uint8Array) => Promise<{ ok: boolean; error?: string }>;
    finish: (sessionId: string, audioClips: any[]) => Promise<any>;
    cancel: (sessionId: string) => Promise<boolean>;
  };

  /** Write generated bytes to a temp file, so ffmpeg can read them. */
  media: {
    writeTemp: (name: string, bytes: Uint8Array) => Promise<string>;
    /**
     * Enumerate a folder. The renderer cannot: `fetch`/XHR on a `file://`
     * directory both fail even with webSecurity off. Reports names, sizes
     * and timestamps only — whether a file is usable media is decided by
     * trying to decode it, not by its extension.
     */
    listFolder: (
      path: string,
      recursive?: boolean
    ) => Promise<{
      ok: boolean;
      folder?: string;
      entries?: {
        name: string; path: string; kind: 'file' | 'directory' | 'other';
        sizeBytes: number; mtimeMs: number; birthtimeMs: number;
      }[];
      unreadable?: { name: string; reason: string }[];
      error?: string;
    }>;
  };

  project: {
    read: (path: string) => Promise<{ ok: boolean; json?: string; error?: string }>;
    write: (path: string, json: string) => Promise<{ ok: boolean; bytes?: number; error?: string }>;
  };

  ffmpeg: {
    process: (opts: {
      input: string; vf?: string; af?: string; fps?: number;
      codec?: 'h264' | 'prores'; noAudio?: boolean; audioOnly?: boolean; name?: string;
    }) => Promise<{ ok: boolean; path?: string; bytes?: number; error?: string }>;
  };

  /** Renderer failures, into the log file main owns. */
  crash: {
    report: (payload: { message: string; detail?: string; source?: string })
      => Promise<{ ok: boolean; logPath: string }>;
    logPath: () => Promise<string>;
  };

  /**
   * Screen and camera capture.
   *
   * The renderer owns the MediaRecorder — only it can hold a
   * MediaStream — and main owns everything a MediaRecorder cannot
   * reach: the source list, the files on disk, the cursor track and
   * the floating control bar.
   */
  recorder: {
    sources: (thumbWidth?: number) => Promise<{
      ok: boolean; error?: string; deniedDespiteSettings?: boolean; sources: RecorderSource[];
    }>;
    /** Clear a stale macOS screen-recording grant so it is asked for again. */
    resetScreenPermission: () => Promise<{ ok: boolean; message: string }>;
    relaunch: () => Promise<boolean>;
    permissions: () => Promise<RecorderPermissions>;
    requestPermission: (kind: 'camera' | 'microphone' | 'screen' | 'accessibility')
      => Promise<{ granted: boolean; opened: boolean }>;
    begin: (opts: { streams: ('screen' | 'camera')[]; displayId: number | null; hideWindow: boolean })
      => Promise<
        | { ok: true; sessionId: string; dir: string; cursorTracked: boolean; shortcuts: string[]; barHiddenFromCapture: boolean }
        | { ok: false; error: string }
      >;
    chunk: (sessionId: string, stream: 'screen' | 'camera', bytes: Uint8Array)
      => Promise<{ ok: boolean; bytes?: number; error?: string }>;
    pause: (sessionId: string, paused: boolean) => Promise<{ ok: boolean; elapsedMs?: number }>;
    finish: (sessionId: string, copyable: boolean) => Promise<any>;
    cancel: (sessionId: string, discard: boolean) => Promise<{ ok: boolean; dir?: string; discarded?: boolean }>;
    writeTakeAsset: (dir: string, name: string, bytes: Uint8Array) => Promise<any>;
    /** A take's cursor.json, decrypted if it is sealed. */
    readManifest: (dir: string) => Promise<any>;
    reveal: (path: string) => Promise<boolean>;
    /** Push what the floating bar shows. */
    publishState: (state: Record<string, unknown>) => Promise<boolean>;
    /** The bar's buttons, on their way to the window that is recording. */
    barCommand: (action: string) => Promise<boolean>;
    onCommand: (cb: (p: { action: string; source: string }) => void) => () => void;
    onState: (cb: (state: Record<string, unknown>) => void) => () => void;
  };

  /** How many times a skill on trial has been run, held sealed in main. */
  trials: {
    status: (skillId: string, allowed: number, owned: boolean, scope?: string)
      => Promise<TrialStatus>;
    consume: (skillId: string, allowed: number, owned: boolean, scope?: string)
      => Promise<{ ok: boolean; status: TrialStatus }>;
    clearBought: (skillId: string) => Promise<{ ok: boolean }>;
  };

  /** Screen state, so the window close button can mean the right thing. */
  ui: {
    setScreen: (screen: 'home' | 'editor') => Promise<boolean>;
    onGoHome: (cb: () => void) => () => void;
  };

  /** The Kerf Store session token, held at 0600 in main rather than
      in the renderer's localStorage. */
  store: {
    getSession: () => Promise<{ session: { token: string; expiresAt: number } | null; baseUrl: string }>;
    setSession: (token: string, expiresAt: number) => Promise<boolean>;
    clearSession: () => Promise<boolean>;
  };

  /** Which CLI backend drives the Copilot, and getting one installed. */
  agents: {
    list: (deep?: boolean) => Promise<{ selected: string; backends: unknown[] }>;
    select: (id: string) => Promise<string>;
    install: (id: string) => Promise<{ ok: boolean; message: string }>;
    setKey: (variable: string, value: string) => Promise<boolean>;
    recheck: () => Promise<boolean>;
    models: (id: string) => Promise<{ models: string[]; source: string; selected: string }>;
    setModel: (id: string, model: string) => Promise<boolean>;
    signIn: (id: string) => Promise<{ ok: boolean; message: string }>;
    onInstallProgress: (cb: (p: { id: string; line: string }) => void) => () => void;
  };

  /** The Claude Code session that powers the Copilot. */
  claude: {
    status: () => Promise<ClaudeStatus>;
    send: (prompt: string, resume: boolean) => Promise<boolean>;
    stop: () => Promise<boolean>;
    reset: () => Promise<boolean>;
    onEvent: (cb: (event: Record<string, unknown>) => void) => () => void;
  };

  updater: {
    /** Current state, for the first render before any event arrives. */
    getStatus: () => Promise<UpdateStatus>;
    getCurrentVersion: () => Promise<string>;
    /** User-initiated check. Background checks happen on their own. */
    check: () => Promise<UpdateStatus>;
    /** Quit and apply a downloaded update. No-op unless state is `ready`. */
    install: () => Promise<boolean>;
    /** Fallback for builds that cannot self-update. */
    openReleases: () => Promise<void>;
    /** Subscribe to state changes; returns an unsubscribe function. */
    onStatus: (cb: (status: UpdateStatus) => void) => () => void;
  };
}

const api: ElectronAPI = {
  openMediaDialog: () => ipcRenderer.invoke('dialog:openMedia'),
  saveExportDialog: (defaultName: string) => ipcRenderer.invoke('dialog:saveExport', defaultName),
  platform: process.platform,

  bridge: {
    onListTools: (cb) => {
      ipcRenderer.on('bridge:list-tools', (_e, msg: { id: string }) => cb(msg.id));
    },
    onCallTool: (cb) => {
      ipcRenderer.on(
        'bridge:call-tool',
        (_e, msg: { id: string; payload: { name: string; args: Record<string, unknown> } }) =>
          cb(msg.id, msg.payload.name, msg.payload.args)
      );
    },
    respond: (payload) => ipcRenderer.send('bridge:response', payload),
  },

  stt: {
    status: () => ipcRenderer.invoke('stt:status'),
    transcribe: (opts) => ipcRenderer.invoke('stt:transcribe', opts),
    analyze: (opts) => ipcRenderer.invoke('audio:analyze', opts),
    setup: (opts) => ipcRenderer.invoke('stt:setup', opts ?? {}),
    onProgress: (cb) => {
      const handler = (_e: unknown, p: { percent: number; note: string }) => cb(p);
      ipcRenderer.on('stt:progress', handler);
      return () => ipcRenderer.removeListener('stt:progress', handler);
    },
  },

  exporter: {
    start: (opts) => ipcRenderer.invoke('export:start', opts),
    frame: (sessionId, jpeg) => ipcRenderer.invoke('export:frame', { sessionId, jpeg }),
    finish: (sessionId, audioClips) => ipcRenderer.invoke('export:finish', { sessionId, audioClips }),
    cancel: (sessionId) => ipcRenderer.invoke('export:cancel', { sessionId }),
  },

  media: {
    writeTemp: (name, bytes) => ipcRenderer.invoke('media:writeTemp', { name, bytes }),
    listFolder: (path, recursive) => ipcRenderer.invoke('media:listFolder', { path, recursive }),
  },

  project: {
    read: (filePath) => ipcRenderer.invoke('project:read', { path: filePath }),
    write: (filePath, json) => ipcRenderer.invoke('project:write', { path: filePath, json }),
  },

  ffmpeg: {
    process: (opts) => ipcRenderer.invoke('ffmpeg:process', opts),
  },

  crash: {
    report: (payload) => ipcRenderer.invoke('crash:report', payload),
    logPath: () => ipcRenderer.invoke('crash:logPath'),
  },
  recorder: {
    sources: (thumbWidth) => ipcRenderer.invoke('recorder:sources', { thumbWidth }),
    resetScreenPermission: () => ipcRenderer.invoke('recorder:resetScreenPermission'),
    relaunch: () => ipcRenderer.invoke('recorder:relaunch'),
    permissions: () => ipcRenderer.invoke('recorder:permissions'),
    requestPermission: (kind) => ipcRenderer.invoke('recorder:requestPermission', { kind }),
    begin: (opts) => ipcRenderer.invoke('recorder:begin', opts),
    chunk: (sessionId, stream, bytes) => ipcRenderer.invoke('recorder:chunk', { sessionId, stream, bytes }),
    pause: (sessionId, paused) => ipcRenderer.invoke('recorder:pause', { sessionId, paused }),
    finish: (sessionId, copyable) => ipcRenderer.invoke('recorder:finish', { sessionId, copyable }),
    cancel: (sessionId, discard) => ipcRenderer.invoke('recorder:cancel', { sessionId, discard }),
    writeTakeAsset: (dir, name, bytes) =>
      ipcRenderer.invoke('recorder:writeTakeAsset', { dir, name, bytes }),
    readManifest: (dir) => ipcRenderer.invoke('recorder:readManifest', { dir }),
    reveal: (filePath) => ipcRenderer.invoke('recorder:reveal', { path: filePath }),
    publishState: (state) => ipcRenderer.invoke('recorder:publishState', state),
    barCommand: (action) => ipcRenderer.invoke('recorder:barCommand', { action }),
    onCommand: (cb) => {
      const handler = (_e: unknown, p: { action: string; source: string }) => cb(p);
      ipcRenderer.on('recorder:command', handler);
      return () => ipcRenderer.removeListener('recorder:command', handler);
    },
    onState: (cb) => {
      const handler = (_e: unknown, state: Record<string, unknown>) => cb(state);
      ipcRenderer.on('recorder:state', handler);
      return () => ipcRenderer.removeListener('recorder:state', handler);
    },
  },

  trials: {
    status: (skillId, allowed, owned, scope) =>
      ipcRenderer.invoke('trials:status', { skillId, allowed, owned, scope }),
    consume: (skillId, allowed, owned, scope) =>
      ipcRenderer.invoke('trials:consume', { skillId, allowed, owned, scope }),
    clearBought: (skillId) => ipcRenderer.invoke('trials:clearBought', { skillId }),
  },

  ui: {
    setScreen: (screen) => ipcRenderer.invoke('ui:setScreen', { screen }),
    onGoHome: (cb) => {
      const handler = () => cb();
      ipcRenderer.on('ui:go-home', handler);
      return () => ipcRenderer.removeListener('ui:go-home', handler);
    },
  },

  store: {
    getSession: () => ipcRenderer.invoke('store:getSession'),
    setSession: (token, expiresAt) => ipcRenderer.invoke('store:setSession', { token, expiresAt }),
    clearSession: () => ipcRenderer.invoke('store:clearSession'),
  },

  agents: {
    list: (deep) => ipcRenderer.invoke('agents:list', { deep }),
    select: (id) => ipcRenderer.invoke('agents:select', { id }),
    install: (id) => ipcRenderer.invoke('agents:install', { id }),
    setKey: (variable, value) => ipcRenderer.invoke('agents:setKey', { variable, value }),
    recheck: () => ipcRenderer.invoke('agents:recheck'),
    models: (id) => ipcRenderer.invoke('agents:models', { id }),
    setModel: (id, model) => ipcRenderer.invoke('agents:setModel', { id, model }),
    signIn: (id) => ipcRenderer.invoke('agents:signIn', { id }),
    onInstallProgress: (cb) => {
      const handler = (_e: unknown, p: { id: string; line: string }) => cb(p);
      ipcRenderer.on('agents:install-progress', handler);
      return () => ipcRenderer.removeListener('agents:install-progress', handler);
    },
  },

  claude: {
    status: () => ipcRenderer.invoke('claude:status'),
    send: (prompt: string, resume: boolean) => ipcRenderer.invoke('claude:send', { prompt, resume }),
    stop: () => ipcRenderer.invoke('claude:stop'),
    reset: () => ipcRenderer.invoke('claude:reset'),
    onEvent: (cb) => {
      const handler = (_e: unknown, event: Record<string, unknown>) => cb(event);
      ipcRenderer.on('claude:event', handler);
      return () => ipcRenderer.removeListener('claude:event', handler);
    },
  },

  updater: {
    getStatus: () => ipcRenderer.invoke('updater:status'),
    getCurrentVersion: () => ipcRenderer.invoke('updater:currentVersion'),
    check: () => ipcRenderer.invoke('updater:check'),
    install: () => ipcRenderer.invoke('updater:install'),
    openReleases: () => ipcRenderer.invoke('updater:openReleases'),
    onStatus: (cb) => {
      const handler = (_e: unknown, status: UpdateStatus) => cb(status);
      ipcRenderer.on('updater:status', handler);
      return () => ipcRenderer.removeListener('updater:status', handler);
    },
  },
};

contextBridge.exposeInMainWorld('electronAPI', api);
